2020-02-06 20:30:56,546 | ERROR   | [Errno 2] No such file or directory: '. /root/code/sibsutis-timetable/status.sh': '. /root/code/sibsutis-timetable/status.sh'
Traceback (most recent call last):
  File "main.py", line 182, in send_server
    call([". /root/code/sibsutis-timetable/status.sh"])
  File "/home/root/.python/lib/python3.7/subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/root/.python/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/home/root/.python/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '. /root/code/sibsutis-timetable/status.sh': '. /root/code/sibsutis-timetable/status.sh'
2020-02-06 20:31:25,751 | ERROR   | [Errno 2] No such file or directory: '. /root/code/sibsutis-timetable/status.sh': '. /root/code/sibsutis-timetable/status.sh'
Traceback (most recent call last):
  File "main.py", line 182, in send_server
    call([". /root/code/sibsutis-timetable/status.sh"])
  File "/home/root/.python/lib/python3.7/subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/root/.python/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/home/root/.python/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '. /root/code/sibsutis-timetable/status.sh': '. /root/code/sibsutis-timetable/status.sh'
2020-02-06 20:32:06,623 | ERROR   | [Errno 2] No such file or directory: '~/code/sibsutis-timetable/status.sh': '~/code/sibsutis-timetable/status.sh'
Traceback (most recent call last):
  File "main.py", line 182, in send_server
    call(["~/code/sibsutis-timetable/status.sh"])
  File "/home/root/.python/lib/python3.7/subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/root/.python/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/home/root/.python/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '~/code/sibsutis-timetable/status.sh': '~/code/sibsutis-timetable/status.sh'
2020-02-06 20:33:39,379 | ERROR   | [Errno 13] Permission denied: '/root/code/sibsutis-timetable/status.sh'
Traceback (most recent call last):
  File "main.py", line 182, in send_server
    call(["/root/code/sibsutis-timetable/status.sh"])
  File "/home/root/.python/lib/python3.7/subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/root/.python/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/home/root/.python/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/root/code/sibsutis-timetable/status.sh'
2020-02-06 20:34:44,712 | ERROR   | [Errno 2] No such file or directory: '/root/code/sibsutis-timetable/status.sh': '/root/code/sibsutis-timetable/status.sh'
Traceback (most recent call last):
  File "main.py", line 182, in send_server
    call(["/root/code/sibsutis-timetable/status.sh"])
  File "/home/root/.python/lib/python3.7/subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/root/.python/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/home/root/.python/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/root/code/sibsutis-timetable/status.sh': '/root/code/sibsutis-timetable/status.sh'
